### ISSUE TITLE
Making the package compatible with composer/packagist

### ISSUE THREAD

**Issue by haakym** [joeblurton/doccounter#6]
Firstly, thanks for putting this repo together.

Secondly, would you accept pull requests that would reshape this repo to be compatible with composer/packagist? Alternatively, I will create a fork so there would be a composer/packagist compatible version.

**Comment by joeblurton** [comment]
Hi, the specific requirement for this package was for it to worked on shared hosting solutions, i.e. where composer cannot be installed. That’s been a significant limiting factor and I have since decided to reimplement the library using command line tools instead. For you to do as you desire, I suggest a fork. But any upgrades in functionality would be most welcome as a pull request.
